// web-vue/src/Login.vue
<script lang="ts" setup>
import { ref } from "vue";
import Cookies from "js-cookie"
import { useRouter } from "vue-router"
import { useI18n } from "vue-i18n"
import { storage } from "./Env";
const router = useRouter()
const { t } = useI18n({ inheritLocale: true })
const account = ref("")
const password = ref("")
const showPassword = ref(false)
const isLogingIn = ref(false)
const showErrorDialog = ref(false)

const errorCause = ref("")

async function login(event) {
  const result = await event;
  if (!result.valid) {
    return;
  }
  if (!account.value) {
    // if no account is posted, assume password is not required.
    router.push("/view")
  }
  isLogingIn.value = true
  try {
    const loginRes = await fetch("/api/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        account: account.value,
        password: password.value,
      })
    })
    if (loginRes.ok) {
      const { jwt } = await loginRes.json()
      Cookies.set("jwt", jwt)
      const lastPath = storage.lastFilePathFromUrl
      if (lastPath) {
        router.push(`/view?file=${encodeURIComponent(lastPath)}`)
      } else {
        router.push("/view")
      }
    } else {
      const cause = await loginRes.text()
      throw new Error(cause)
    }
  } catch (error) {
    console.error(error)
    errorCause.value = error.message
    showErrorDialog.value = true
  } finally {
    isLogingIn.value = false
  }
}

</script>
<template>
  <div class="dialog">
    <v-sheet rounded width="450" class="mx-auto sheet">
      <v-card-title>
        <h2 style="text-align: center">
          {{ t("login.title") }}
        </h2>
      </v-card-title>
      <v-form validate-on="submit" @submit.prevent="login" :loading="isLogingIn">
        <v-card-text>
          <v-text-field v-model="account" :label="t('login.account')"></v-text-field>
          <v-text-field v-model="password" :append-icon="showPassword ? 'mdi-eye' : 'mdi-eye-off'"
            :type="showPassword ? 'text' : 'password'" :label="t('login.password')"
            @click:append="showPassword = !showPassword"></v-text-field>
        </v-card-text>
        <v-card-actions>
          <v-btn color="primary" :disabled="isLogingIn" rounded type="submit">
            {{ t("login.loginBtn") }}
          </v-btn>
        </v-card-actions>
      </v-form>
    </v-sheet>
  </div>

  <v-dialog v-model="showErrorDialog" width="auto">
    <v-card>
      <v-card-text>{{ t("login.failed") }}</v-card-text>
      <v-card-actions>
        <v-btn color="primary" @click="showErrorDialog = false">
          {{ t("login.closeBtn") }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.dialog {
  display: flex;
  place-items: center;
  min-height: 100vh;
}

.sheet {
  border-radius: 16px;
}
</style>

// web-react/src/pages/Login.jsx
import "./Login.css"
import { Button, DialogActions, Card, InputAdornment, IconButton, TextField, Dialog, DialogTitle } from "@mui/material"
import React, { useEffect, useState } from "react"
import {
  redirect,
  useNavigate
} from "react-router-dom"
import { storage, updatePageTitle } from "../Env.js"
import { i18n } from "../I18n.js"
import { Visibility, VisibilityOff } from "@mui/icons-material"
import Cookies from "js-cookie"

// Skip login if jwt is still valid.
export async function loader() {
  // try to verify the jwt, or the backend doesn't require jwt.
  const validationRes = await fetch("/verify")
  if (validationRes.ok) {
    return redirect("/view")
  } else {
    Cookies.remove("jwt")
    return null
  }
}

export function LoginDialog() {
  useEffect(() => {
    updatePageTitle(i18n.login.title)
  }, [])
  const navigate = useNavigate()
  const [account, setAccount] = useState("")
  const [password, setPassword] = useState("")
  const [showPassword, setShowPassword] = useState(false)
  const [failedDialogOpen, setFailedDialogOpen] = React.useState(false)
  const onLogin = async () => {
    const loginRes = await fetch("/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        account, password,
      })
    })
    if (loginRes.ok) {
      const { jwt } = await loginRes.json()
      Cookies.set("jwt", jwt)
      const lastPath = storage.lastFilePathFromUrl
      if (lastPath) {
        navigate(`/view?file=${encodeURIComponent(lastPath)}`)
      } else {
        navigate("/view")
      }
    } else {
      Cookies.remove("jwt")
      setFailedDialogOpen(true)
    }
  }
  return (
    <>
      <Card id="login-dialog">
        <h1>{i18n.login.title}</h1>
        <form id="login-form" style={{
          flexDirection: "column", display: "flex",
        }} onSubmit={(e) => {
          onLogin()
          e.preventDefault()
        }}>
          <TextField
            variant="outlined"
            type='text'
            label={i18n.login.account}
            onChange={(e) => setAccount(e.target.value)}
          />
          <TextField
            variant="outlined"
            type={showPassword ? "text" : "password"}
            label={i18n.login.password}
            onChange={(e) => setPassword(e.target.value)}
            InputProps={{
              endAdornment: <InputAdornment position="end">
                <IconButton
                  onClick={() => { setShowPassword(!showPassword) }}
                  onMouseDown={() => { setShowPassword(!showPassword) }}
                  aria-label="toggle-password-visibility"
                >
                  {showPassword ? <Visibility /> : <VisibilityOff />}
                </IconButton>
              </InputAdornment>
            }}
          />
          <DialogActions>
            <Button type="submit">{i18n.login.loginBtn}</Button>
          </DialogActions>
        </form>
      </Card>
      <LoginFailedDialog
        open={failedDialogOpen}
        setOpen={setFailedDialogOpen} />
    </>
  )
}

function LoginFailedDialog({ open, setOpen }) {
  const handleClose = () => {
    setOpen(false)
  }
  return (
    <Dialog open={open}>
      <DialogTitle>{i18n.login.failed}</DialogTitle>
      <DialogActions>
        <Button onClick={handleClose} autoFocus>
          {i18n.login.closeBtn}
        </Button>
      </DialogActions>
    </Dialog>
  )
}
